SET CLIENT_MIN_MESSAGES TO WARNING;
SET CLIENT_ENCODING = 'UTF8';
DROP SCHEMA IF EXISTS main CASCADE;
SET CLIENT_MIN_MESSAGES TO INFO;
SET CLIENT_ENCODING = 'UTF8';
CREATE SCHEMA main;
-- SET SEARCH_PATH = main;
CREATE EXTENSION pg_trgm SCHEMA main;
CREATE EXTENSION pgcrypto SCHEMA main;
CREATE TABLE main.containers (
  id UUID PRIMARY KEY DEFAULT main.gen_random_uuid(),
  name VARCHAR(128) NOT NULL UNIQUE CHECK (name <> ''),
  image VARCHAR(128) NOT NULL CHECK (image <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
